name: Basic CI

on:
  push:
    branches:
      - learning/github-actions
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    services:
        mongodb:
          image: mongo:7
          ports:
            - 27017:27017
          env:
            MONGO_INITDB_DATABASE: jamitizedb
            MONGO_INITDB_ROOT_USERNAME: jamitize-user
            MONGO_INITDB_ROOT_PASSWORD: jamitize-user
          options: >-
            --health-cmd="mongosh --quiet --eval 'db.adminCommand({ ping: 1 })'"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=5
          

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      
      - name: Verify Go Installation
        run:  |
          go version
          go env GOPATH

      - name: Install Go Dependencies
        run: go mod download
      
      - name: Create application database user
        run: |
          CONTAINER_ID=$(docker ps --filter "ancestor=mongo:7" --format "{{.ID}}" | head -n 1)

          docker exec -i "$CONTAINER_ID" mongosh \
            -u jamitize-user \
            -p jamitize-user \
            --authenticationDatabase admin <<'EOF'
          use jamitizedb
          db.createUser({
            user: "jamitize-user",
            pwd: "jamitize-user",
            roles: [
              { role: "readWrite", db: "jamitizedb" }
            ]
          })
          EOF
      
      - name: Initialize schema
        run: |
          CONTAINER_ID=$(docker ps --filter "ancestor=mongo:7" --format "{{.ID}}" | head -n 1)
          docker exec -i "$CONTAINER_ID" mongosh \
            "mongodb://jamitize-user:jamitize-user@localhost:27017/jamitizedb?authSource=admin" \
            < db/schema.js

      - name: Run tests
        env:
          ENVIRONMENT: dev
          MONGODB_HOST: localhost
          MONGODB_PORT: "27017"
          MONGODB_DATABASE: jamitizedb
          MONGODB_USERNAME: jamitize-user
          MONGODB_PASSWORD: jamitize-user
          JWT_SECRET: test-secret
          LOG_URL: ""
        run: go test ./...

  run_docker:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@v4

      - name: Create temporary .env
        run: |
          cat > .env <<EOF
          ENVIRONMENT=prod
          MONGODB_HOST=localhost
          MONGODB_PORT=27017
          MONGODB_DATABASE=jamitizedb
          MONGODB_USERNAME=jamitize-user
          MONGODB_PASSWORD=jamitize-user
          JWT_SECRET=test-secret
          LOG_URL=
          EOF

      - name: Build Docker image
        run: docker build -t jamitize .
      
