name: Deploy to AWS

on:
    workflow_dispatch:
    push:
        tags:
            - "v*"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Check Secrets
              run: |
                  echo "${{ secrets.EC2_HOST }}" \
                  echo "${{ secrets.EC2_SSH_KEY }}"

            - name: Copy deployment files to EC2
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  port: ${{ secrets.EC2_PORT || 30 }}
                  source: "docker-compose-prod.yml,db"
                  target: "/home/${{ secrets.EC2_USER }}/jamitize"

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  port: ${{ secrets.EC2_PORT || 30 }}
                  script: |
                      cd /home/ubuntu/jamitize

                      docker compose -f docker-compose-prod.yml pull
                      docker compose -f docker-compose-prod.yml up -d

                      docker compose -f docker-compose-prod.yml ps
